name: Exercise6 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 20
    steps:
    - name: Clone the Github repository on the machine
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
      
    - name: Install dependencies on the machine
      uses: npm install

    - name: Run npm security tests
      uses: npm audit

  build:
    runs-on: ubuntu-latest
    needs: security_tests

    strategy:
      fail-fast: true
      matrix:
        node-version: 20
    steps:
    - name: Clone repo on machine
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: install dependencies
      run: npm install

    - name: Start the app
      run: npm run start &
      
    - name: Run tests
      run: npm test

    - name: Upload test output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-output.log
